# site basics
title: "Pooja Manwani"
email: "manwanii.pooja@gmail.com"
description: "PhD Research Scholar | Climate Studies | IIT Bombay"
baseurl: ""        # leave empty for user sites
url: "https://poojamanwani12.github.io"

# Minimal Mistakes remote theme (required)
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme

# build settings
markdown: kramdown
permalink: pretty

# author/sidebar info
author:
  name: "Pooja Manwani"
  avatar: "/assets/img/profile.jpg"  # optional; create this file later or remove line
  bio: "PhD Research Scholar | Climate Studies, IIT Bombay"
  email: "manwanii.pooja@gmail.com"

# social links (sidebar)
social:
  - label: "Google Scholar"
    icon: "fas fa-graduation-cap"
    url: "https://scholar.google.com/citations?user=wiqeOswAAAAJ&hl=en"
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/poojamanwani12"
  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "#"

# Tell theme where navigation lives
include: [_data]
